name: Latest Youtube Videos
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from Youtube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/actionst@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCDCHcqyeQgJ-jVSd6VJkbCw"
          # feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCn1nfBWKVmvPvTsAH5Agf6Q"
